trigger:
- master

pool:
  name: WaveEngine

variables:
  - group: Versions
  - name: 'nugetConfigPath'
    value: '$(Build.SourcesDirectory)/OpenXRGen/WaveEngine.Bindings.OpenXR/NuGet.config'
  - name: 'nugetOutputPath'
    value: '$(Build.StagingDirectory)/nupkgs'
  - name: 'appversion'
    value: '$(version.major).$(version.minor).$(version.patch).$(Build.BuildID)-$(version.previewSuffix)'

workspace:
  clean: all

steps:

- task: UseDotNet@2
  displayName: 'Check .NETCore SDK'
  inputs:
    version: '$(NetCoreSDKVersion)'

- task: NuGetToolInstaller@1
  displayName: 'Check NuGet client'
  inputs:
    versionSpec: '$(NuGetVersion)'
    checkLatest: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '"<configuration></configuration>" > $(nugetConfigPath)'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources add -Name "WaveNightlyFeed" -Source "https://waveengineteam.pkgs.visualstudio.com/_packaging/WaveEngine-nightly/nuget/v3/index.json" -Username "vsts" -Password "$(WaveNightlyToken)" -StorePasswordInClearText -ConfigFile $(nugetConfigPath)'

- task: PowerShell@2
  displayName: 'Generate NuGet packages'
  inputs:
    filePath: './Generate-NuGets.ps1'
    arguments: '-Version $(appversion) -outputfolder $(nugetOutputPath)'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: NuGets"
  inputs:
    PathtoPublish: '$(nugetOutputPath)'
    ArtifactName: 'NuGets'
    publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: 'Push NuGets to NuGet.org'
  inputs:
    command: 'push'
    packagesToPush: '$(nugetOutputPath)/**/*.nupkg;!$(nugetOutputPath)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'WaveEngine Nuget.org'
