using System;
using System.Collections.Generic;
using System.Text;

namespace Evergine.Bindings.OpenXR
{
	[Flags]
	public enum VkImageUsageFlags
	{
		None = 0,
		VK_IMAGE_USAGE_TRANSFER_SRC_BIT = 1,
		VK_IMAGE_USAGE_TRANSFER_DST_BIT = 2,
		VK_IMAGE_USAGE_SAMPLED_BIT = 4,
		VK_IMAGE_USAGE_STORAGE_BIT = 8,
		VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 16,
		VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 32,
		VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT = 64,
		VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 128,
		VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR = 1024,
		VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR = 2048,
		VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR = 4096,
		VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT = 512,
		VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 256,
		VK_IMAGE_USAGE_VIDEO_ENCODE_DST_BIT_KHR = 8192,
		VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR = 16384,
		VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR = 32768,
		VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI = 262144,
	}
}
