name: Update_and_Commit
on:
  [push]
  #schedule:
  #- cron: '0 0 1 * *'
      
jobs:   
  download:
    env:
      xrFile: ${{  'xr.xml'  }}
      xrTmpFile: ${{  'xr.xml_tmp'  }}
      xrPath: ${{  'KhronosRegistry'  }}
      xrUrl: ${{  'https://raw.githubusercontent.com/KhronosGroup/OpenXR-Docs/master/specification/registry/xr.xml'  }}
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v2      
      - name: download xr file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: ${{  env.xrUrl  }}
          file-name: ${{  env.xrTmpFile  }}
          location: ${{ env.xrPath  }}/
      - name: Get hash from saved xr
        id: xr        
        run: |
          echo "::set-output name=hash1::${{ hashFiles('./KhronosRegistry/xr.xml')  }}"
          echo "::set-output name=hash2::${{ hashFiles('./KhronosRegistry/xr.xml_tmp')  }}"      
      - name: Compare and update files
        if: ${{ steps.xr.outputs.hash1 != steps.xr.outputs.hash2  }}
        run: |
            echo "${{  steps.xr.outputs.hash1  }} ${{  steps.xr.outputs.hash2  }}"
            cd ${{  env.xrPath  }}
            rm ${{  env.xrFile  }} 
            mv ${{  env.xrTmpFile  }}  ${{  env.xrFile  }}
            ls
      - name: Commit if update
        if: ${{ steps.xr.outputs.hash1 != steps.xr.outputs.hash2  }}
        uses: zwaldowski/git-commit-action@v1        
        with:
          commit_message: Updating new xr file
