name: Update_and_Commit
on:
  [push]
  #schedule:
  #- cron: '0 0 1 * *'
 
jobs:
  build:
    runs-on: windows-latest
    env:
      xrFile: ${{  'xr.xml'  }}
      xrTmpFile: ${{  'xr.xml_tmp'  }}
      xrPath: ${{  'KhronosRegistry'  }}
      xrUrl: ${{  'https://raw.githubusercontent.com/KhronosGroup/OpenXR-Docs/master/specification/registry/xr.xml'  }}
    steps:
      - uses: actions/checkout@v2      
      - name: download xr file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: ${{  env.xrUrl  }}
          file-name: ${{  env.xrTmpFile  }}
          location: ${{ env.xrPath  }}/
      - name: Compare files
        if: ${{  hashFiles('./${{  env.xrPath  }}/${{  env.xrFile  }}')  }} != ${{  hashFiles('./${{  env.xrPath  }}/${{  env.xrTmpFile  }}')  }}
        run: echo "DIFF=true" >> "$GITHUB_ENV"
      - name: Replace if Different
        if: ${{ env.DIFF  }}
        run: |
          cd ${{  env.xrPath  }}
          ls
          rm ${{  env.xrFile  }} 
          mv ${{  env.xrTmpFile  }}  ${{  env.xrFile  }}
          ls
        
