name: Update_and_Commit
on:
  [push]
  #schedule:
  #- cron: '0 0 1 * *'

env:
  xrFile: ${{  'xr.xml'  }}
  xrTmpFile: ${{  'xr.xml_tmp'  }}
  xrPath: ${{  'KhronosRegistry'  }}
  xrUrl: ${{  'https://raw.githubusercontent.com/KhronosGroup/OpenXR-Docs/master/specification/registry/xr.xml'  }}
      
jobs:   
  download:
    runs-on: windows-latest 
    outputs:
      hash1: ${{ steps.xr.outputs.hash }}
      hash2: ${{ steps.xrNEW.outputs.hash }}
    steps:
      - uses: actions/checkout@v2      
      - name: download xr file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: ${{  env.xrUrl  }}
          file-name: ${{  env.xrTmpFile  }}
          location: ${{ env.xrPath  }}/
      - id: xr
        name: Get hash from saved xr
        run: echo "::set-output name=hash::${{ hashFiles('./KhronosRegistry/xr.xml')  }}"
      - id: xrNEW
        name: Get hash from current xr
        run: echo "::set-output name=hash::${{ hashFiles('${{  env.xrPath  }}/${{  env.xrTmpFile  }}')  }}"
        
  compare:
    runs-on: windows-latest
    needs: download
    steps:
      - name: Compare files
        if: ${{needs.download.outputs.hash1}} == ${{needs.download.outputs.hash2}}
        run: |
            cd ${{  env.xrPath  }}
            ls
            rm ${{  env.xrFile  }} 
            mv ${{  env.xrTmpFile  }}  ${{  env.xrFile  }}
            ls
