name: Update_and_Generate_NuGet
on:
  schedule:
  - cron: '0 0 1 * *'
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.1
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Copy config path
        run: '"<configuration></configuration>" > $(nugetConfigPath)'
      - name: Add WaveNightlyFeed
        run: sources add -Name "WaveNightlyFeed" -Source "https://waveengineteam.pkgs.visualstudio.com/_packaging/WaveEngine-nightly/nuget/v3/index.json" -Username "vsts" -Password "$(WaveNightlyToken)" -StorePasswordInClearText -ConfigFile $(nugetConfigPath)'
      - name: Generate NuGet packages
        run: powershell ./Generate-NuGets.ps1 -Version $(appversion) -outputfolder $(nugetOutputPath)
