name: Update_and_Generate_NuGet
on:
  [push]
  #schedule:
  #- cron: '0 0 1 * *'
jobs:
  build:
    runs-on: windows-latest
    env:
      xrFile: ${{  'xr.xml'  }}
      xrTmpFile: ${{  'xr.xml_tmp'  }}
      xrPath: ${{  'KhronosRegistry'  }}
      xrUrl: ${{  'https://raw.githubusercontent.com/KhronosGroup/OpenXR-Docs/master/specification/registry/xr.xml'  }}
      diff: ${{  'false'  }}
    steps:
      - uses: actions/checkout@v2      
      - name: download xr file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: ${{  env.xrUrl  }}
          file-name: ${{  env.xrTmpFile  }}
          location: ${{ env.xrPath  }}/
      - name: Compare files
        uses: tianhaoz95-actions/file-diff@v1.0.0
        with:
          # The LHS file to compare
          lhs: ${{ env.xrPath  }}/${{  env.xrTmpFile  }}
          # The RHS file to compare
          rhs: ${{ env.xrPath  }}/${{  env.xrFile  }}
          compare: ${{ env.diff  }}
      - name: Replace if Different
        if: ${{ env.diff  }}
        run: |
          cd ${{ env.xrPath  }}
          rm ${{  env.xrFile  }} 
          mv ${{  env.xrTmpFile  }}  ${{  env.xrFile  }}
        
