name: Update_and_Commit
on:
  [push]
  #schedule:
  #- cron: '0 0 1 * *'

env:
  xrFile: ${{  'xr.xml'  }}
  xrTmpFile: ${{  'xr.xml_tmp'  }}
  xrPath: ${{  'KhronosRegistry'  }}
  xrUrl: ${{  'https://raw.githubusercontent.com/KhronosGroup/OpenXR-Docs/master/specification/registry/xr.xml'  }}
  nugetConfigPath: ${{ 'OpenXRGen/WaveEngine.Bindings.OpenXR/NuGet.config'  }}
  nugetOutputPath: ${{  'nupkgs'  }}

jobs:   
  download:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2      
      - name: download xr file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: ${{  env.xrUrl  }}
          file-name: ${{  env.xrTmpFile  }}
          location: ${{ env.xrPath  }}/
      - name: Get hash from saved xr
        id: xr        
        run: |
          echo "::set-output name=hash1::${{ hashFiles('./KhronosRegistry/xr.xml')  }}"
          echo "::set-output name=hash2::${{ hashFiles('./KhronosRegistry/xr.xml_tmp')  }}"      
      - name: Compare and update files
        if: ${{ steps.xr.outputs.hash1 != steps.xr.outputs.hash2  }}
        run: |
            echo "${{  steps.xr.outputs.hash1  }} ${{  steps.xr.outputs.hash2  }}"
            cd ${{  env.xrPath  }}
            rm ${{  env.xrFile  }} 
            mv ${{  env.xrTmpFile  }}  ${{  env.xrFile  }}
      - name: Commit if update
        if: ${{ steps.xr.outputs.hash1 != steps.xr.outputs.hash2  }}
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Updating new xr file

  build:
    needs: [download]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.8.x'
      - name: Copy config path
        run: '"<configuration></configuration>" > ${{ env.nugetConfigPath  }}'      
      - name: Generate NuGet packages      
        if: ${{ needs.download.outputs.hash1 != needs.download.outputs.hash2  }}
        run: powershell ./Generate-NuGets.ps1 -Version  3.2.0${{  github.run_number  }}-preview -outputfolder ${{  env.nugetOutputPath  }}
      - uses: actions/upload-artifact@v2
        if: ${{ needs.download.outputs.hash1 != needs.download.outputs.hash2  }}
        with:
          name: nuget
          path: ${{  env.nugetOutputPath  }}/

  test:
    needs: [download]
    runs-on: windows-latest
    steps:
      - name: test
        run: echo ${{ needs.download.outputs.hash1 }} ${{ needs.download.outputs.hash2  }}
