name: Update_and_Commit
on:
  [push]
  #schedule:
  #- cron: '0 0 1 * *'

      
jobs:   
  download:
    env:
      xrFile: ${{  'xr.xml'  }}
      xrTmpFile: ${{  'xr.xml_tmp'  }}
      xrPath: ${{  'KhronosRegistry'  }}
      xrUrl: ${{  'https://raw.githubusercontent.com/KhronosGroup/OpenXR-Docs/master/specification/registry/xr.xml'  }}
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v2      
      - name: download xr file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: ${{  env.xrUrl  }}
          file-name: ${{  env.xrTmpFile  }}
          location: ${{ env.xrPath  }}/
      - name: Get hash from saved xr
        id: xr        
        run: echo "::set-output name=hash1::${{ hashFiles('./KhronosRegistry/xr.xml')  }}"
      - name: Get hash from current xr
        id: xrNEW
        run: echo "::set-output name=hash2::${{ hashFiles('${{  env.xrPath  }}/${{  env.xrTmpFile  }}')  }}"
      - name: Compare files
        if: ${{steps.xr.hash}} == ${{steps.xrNEW.hash}}
        run: |
            cd ${{  env.xrPath  }}
            ls
            rm ${{  env.xrFile  }} 
            mv ${{  env.xrTmpFile  }}  ${{  env.xrFile  }}
            ls
